FROM sequenceiq/spark:1.4.0
ADD	./graph1.txt /data/graph1.txt
ADD ./graph2.txt /data/graph2.txt
ADD ./graph3.txt /data/graph3.txt
ADD ./log4j.properties /usr/local/spark/conf/log4j.properties
ADD ./PageRank_v1.py /src/PageRank_v1.py
